// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bymjocmqygasaqqbtlpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5bWpvY21xeWdhc2FxcWJ0bHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTg2MTAsImV4cCI6MjA2NTEzNDYxMH0.SlxQWC9Pa7P6ekfm6SJZLW_K4BZa30M878aYu1U2lFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);